---
- name: "Install and httpd on webservers"
  hosts: webservers
  become: yes

  tasks:
  - name: "Install HTTPD"
    yum:
      name: httpd
      state: present

  - name: "start the httpd service"
    service:
      name: httpd
      state: started

